//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningResults
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearningResults()
        {
            this.NeuralNetworks_LearningResults = new HashSet<NeuralNetworks_LearningResults>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EpochCount { get; set; }
        public double LearningRate { get; set; }
        public Nullable<double> ErrorLimit { get; set; }
        public int ExamplesLearningCount { get; set; }
        public Nullable<int> ExamplesTestCount { get; set; }
        public Nullable<int> ElapsedTimeMilliseconds { get; set; }
        public double ResultErrorLearningExamples { get; set; }
        public Nullable<double> ResultErrorTestExamples { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeuralNetworks_LearningResults> NeuralNetworks_LearningResults { get; set; }
    }
}
