﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Constructor
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"age", @"age"),new InputOutputColumnPair(@"sex", @"sex"),new InputOutputColumnPair(@"cp", @"cp"),new InputOutputColumnPair(@"trestbps", @"trestbps"),new InputOutputColumnPair(@"chol", @"chol"),new InputOutputColumnPair(@"fbs", @"fbs"),new InputOutputColumnPair(@"restecg", @"restecg"),new InputOutputColumnPair(@"thalach", @"thalach"),new InputOutputColumnPair(@"exang", @"exang"),new InputOutputColumnPair(@"oldpeak", @"oldpeak"),new InputOutputColumnPair(@"slope", @"slope"),new InputOutputColumnPair(@"ca", @"ca"),new InputOutputColumnPair(@"thal", @"thal")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"age",@"sex",@"cp",@"trestbps",@"chol",@"fbs",@"restecg",@"thalach",@"exang",@"oldpeak",@"slope",@"ca",@"thal"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"target", @"target"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=6,FeatureFraction=0.613067620637143F,LabelColumnName=@"target",FeatureColumnName=@"Features"}), labelColumnName: @"target"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
