// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Constructor
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"sex")]
            public float Sex { get; set; }

            [ColumnName(@"cp")]
            public float Cp { get; set; }

            [ColumnName(@"trestbps")]
            public float Trestbps { get; set; }

            [ColumnName(@"chol")]
            public float Chol { get; set; }

            [ColumnName(@"fbs")]
            public float Fbs { get; set; }

            [ColumnName(@"restecg")]
            public float Restecg { get; set; }

            [ColumnName(@"thalach")]
            public float Thalach { get; set; }

            [ColumnName(@"exang")]
            public float Exang { get; set; }

            [ColumnName(@"oldpeak")]
            public float Oldpeak { get; set; }

            [ColumnName(@"slope")]
            public float Slope { get; set; }

            [ColumnName(@"ca")]
            public float Ca { get; set; }

            [ColumnName(@"thal")]
            public float Thal { get; set; }

            [ColumnName(@"target")]
            public float Target { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public float Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
