//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeuralNetworkConstructorEntities : DbContext
    {
        public NeuralNetworkConstructorEntities()
            : base("name=NeuralNetworkConstructorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivationFunctions> ActivationFunctions { get; set; }
        public virtual DbSet<CostFunctions> CostFunctions { get; set; }
        public virtual DbSet<Datasets> Datasets { get; set; }
        public virtual DbSet<LearningResults> LearningResults { get; set; }
        public virtual DbSet<NeuralNetworks> NeuralNetworks { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
