//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeuralNetworks_LearningResults
    {
        public int ID { get; set; }
        public int ID_NeuralNetwork { get; set; }
        public int ID_LearningResults { get; set; }
    
        public virtual LearningResults LearningResults { get; set; }
        public virtual NeuralNetworks NeuralNetworks { get; set; }
    }
}
